In [1]:
import pandas as pd
import numpy as np

# Preparation of Suicide Rates Data

In [3]:
csv_data = pd.read_csv("final_table.csv")
csv_data

FileNotFoundError: [Errno 2] No such file or directory: 'final_table.csv'

## Year distribution

In [ ]:
years = csv_data['year']
years.value_counts()

## Filtering rows from year 2014

In [ ]:
csv_data = csv_data[csv_data['year'] == 2014]
csv_data

## Filtering country and suicide columns

In [ ]:
focus = csv_data[['country', 'suicides/100k pop']]
focus

## Table of Country : Suicides per 100k population

In [ ]:
aggregation_functions = {'suicides/100k pop': 'sum'}
final = focus.groupby(focus['country']).aggregate(aggregation_functions)

In [ ]:
final.describe()

### Alphabetical Order

In [ ]:
final

### Descending Order

In [ ]:
final.sort_values(by = ['suicides/100k pop'], ascending = False)

# Preparation of Country Statistics Data

In [4]:
country_stats = pd.read_csv('country_profile_variables.csv')
print(country_stats.shape)
display(country_stats)

(229, 50)

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6.00,-99

## List of Variables

In [5]:
for col in country_stats.columns:
    print(col)

country
Region
Surface area (km2)
Population in thousands (2017)
Population density (per km2, 2017)
Sex ratio (m per 100 f, 2017)
GDP: Gross domestic product (million current US$)
GDP growth rate (annual %, const. 2005 prices)
GDP per capita (current US$)
Economy: Agriculture (% of GVA)
Economy: Industry (% of GVA)
Economy: Services and other activity (% of GVA)
Employment: Agriculture (% of employed)
Employment: Industry (% of employed)
Employment: Services (% of employed)
Unemployment (% of labour force)
Labour force participation (female/male pop. %)
Agricultural production index (2004-2006=100)
Food production index (2004-2006=100)
International trade: Exports (million US$)
International trade: Imports (million US$)
International trade: Balance (million US$)
Balance of payments, current account (million US$)
Population growth rate (average annual %)
Urban population (% of total population)
Urban population growth rate (average annual %)
Fertility rate, total (live births per woman)
Life expectancy at birth (females/males, years)
Population age distribution (0-14 / 60+ years, %)
International migrant stock (000/% of total pop.)
Refugees and others of concern to UNHCR (in thousands)
Infant mortality rate (per 1000 live births
Health: Total expenditure (% of GDP)
Health: Physicians (per 1000 pop.)
Education: Government expenditure (% of GDP)
Education: Primary gross enrol. ratio (f/m per 100 pop.)
Education: Secondary gross enrol. ratio (f/m per 100 pop.)
Education: Tertiary gross enrol. ratio (f/m per 100 pop.)
Seats held by women in national parliaments %
Mobile-cellular subscriptions (per 100 inhabitants)
Mobile-cellular subscriptions (per 100 inhabitants).1
Individuals using the Internet (per 100 inhabitants)
Threatened species (number)
Forested area (% of land area)
CO2 emission estimates (million tons/tons per capita)
Energy production, primary (Petajoules)
Energy supply per capita (Gigajoules)
Pop. using improved drinking water (urban/rural, %)
Pop. using improved sanitation facilities (urban/rural, %)
Net Official Development Assist. received (% of GNI)

## Filtering Variables

In [6]:
# TODO: Decide if we should filter variables now or after calculating correlations
# i think i have to remove columns like: 'Labour force participation (female/male pop. %)' because the values aren't a number
country_stats.drop(columns=['Labour force participation (female/male pop. %)'], inplace=True)
country_stats.drop(columns=['Life expectancy at birth (females/males, years)'], inplace=True)
country_stats.drop(columns=['Population age distribution (0-14 / 60+ years, %)'], inplace=True)
country_stats.drop(columns=['International migrant stock (000/% of total pop.)'], inplace=True)
country_stats.drop(columns=['Education: Primary gross enrol. ratio (f/m per 100 pop.)'], inplace=True)
country_stats.drop(columns=['Education: Secondary gross enrol. ratio (f/m per 100 pop.)'], inplace=True)
country_stats.drop(columns=['Education: Tertiary gross enrol. ratio (f/m per 100 pop.)'], inplace=True)
country_stats.drop(columns=['Energy supply per capita (Gigajoules)'], inplace=True)
country_stats.drop(columns=['Forested area (% of land area)'], inplace=True)
country_stats.drop(columns=['Pop. using improved drinking water (urban/rural, %)'], inplace=True)
country_stats.drop(columns=['Net Official Development Assist. received (% of GNI)'], inplace=True)

display(country_stats)

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Health: Physicians (per 1000 pop.),Education: Government expenditure (% of GDP),Seats held by women in national parliaments %,Mobile-cellular subscriptions (per 100 inhabitants),Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)","Pop. using improved sanitation facilities (urban/rural, %)"
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,0.3,3.3,27.7,61.6,8.3,42,2.1,63,5,21.43
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,1.3,3.5,22.9,106.4,63.3,130,28.2,84,36,2.96
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,...,...,31.6,113.0,38.2,135,0.8,5900,55,0.05
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,-99,-99.0,...,-99,92,87.9,-99,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,3.7,3.3,32.1,88.1,96.9,13,34.0,1,119,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,-99,-99,-99.0,-99,9.0,89,41.6,-99,26,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,-99,-99.0,-99,-99,49,2.7,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,0.3,...,0.0,68.0,25.1,298,1.0,668,12,2.99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,0.2,...,18.0,74.5,21.0,88,65.6,374,26,3.96
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,0.1,8.4,32.6,84.8,16.4,89,37.2,482,30,6.00

## Filtering Countries
We filtered out the countries from the Country Statistics Data which were not found in Suicide Rates data, and vice versa

In [7]:
countries_suicide = list(set(focus['country'].values))
countries_stats = list(set(country_stats['country'].values))

NameError: name 'focus' is not defined

In [8]:
for index, row in country_stats.iterrows():
    if row['country'] not in countries_suicide:
        country_stats.drop(index, inplace=True)
print(country_stats.shape)
pd.set_option('display.max_columns', None)
country_stats.head()

NameError: name 'countries_suicide' is not defined

In [9]:
for index, row in final.iterrows():
    if index not in countries_stats:
        final.drop(index, inplace=True)
print(final.shape)
final.head()

NameError: name 'final' is not defined

## Cleaning Data
Correction of invalid data and data types

### Correction of Invalid Data

In [10]:
country_stats.loc[country_stats['country'] == 'Singapore', 'Economy: Agriculture (% of GVA)'] = 0.0
country_stats.loc[country_stats['country'] == 'Singapore', 'Refugees and others of concern to UNHCR (in thousands)'] = 0.0
country_stats.loc[country_stats['country'] == 'Oman', 'Threatened species (number)'] = 0.0
country_stats.replace('...', np.nan, inplace = True)
country_stats.replace(-99, np.nan, inplace = True)
display(country_stats)

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Health: Physicians (per 1000 pop.),Education: Government expenditure (% of GDP),Seats held by women in national parliaments %,Mobile-cellular subscriptions (per 100 inhabitants),Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)","Pop. using improved sanitation facilities (urban/rural, %)"
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270.0,-2.4,623.2,23.3,...,0.3,3.3,27.7,61.6,8.3,42.0,2.1,63.0,5.0,21.43
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541.0,2.6,3984.2,22.4,...,1.3,3.5,22.9,106.4,63.3,130.0,28.2,84.0,36.0,2.96
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779.0,3.8,4154.1,12.2,...,NaN,NaN,31.6,113.0,38.2,135.0,0.8,5900.0,55.0,0.05
3,American Samoa,Polynesia,199,56,278.2,103.6,NaN,-99,NaN,-99,...,-99,-99,NaN,NaN,-99,92.0,87.9,NaN,NaN,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812.0,0.8,39896.4,0.5,...,3.7,3.3,32.1,88.1,96.9,13.0,34.0,1.0,119.0,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,NaN,-99,NaN,-99,...,-99,-99,NaN,-99,9.0,89.0,41.6,NaN,26.0,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,NaN,-99,NaN,-99,...,-99,-99,NaN,-99,-99,49.0,2.7,NaN,NaN,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688.0,-28.1,1106.4,14.7,...,0.3,NaN,0.0,68.0,25.1,298.0,1.0,668.0,12.0,2.99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255.0,2.9,1311.1,8.2,...,0.2,NaN,18.0,74.5,21.0,88.0,65.6,374.0,26.0,3.96
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893.0,1.1,890.4,13.0,...,0.1,8.4,32.6,84.8,16.4,89.0,37.2,482.0,30.0,6.00

### Correcting Data Types

In [11]:
for col in list(country_stats.columns.values):
    if col != 'country' and col != 'Region':
        country_stats[col] = country_stats[col].astype(float)
country_stats.dtypes

ValueError: could not convert string to float: '~0'

## Cleaned Country Statistics Data

In [ ]:
final_stats = pd.DataFrame(country_stats)
final_stats.head()

In [ ]:
final_stats.describe()

In [ ]:
print(final_stats.shape)